### ISSUE TITLE
Publishing doesn't use correct version but 0.0.0 instead

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/rebdhuhn#202]
> Run pypa/gh-action-pypi-publish@release/v1
/usr/bin/docker run --name a4d52cd77ac7d645c69bfdf09628f5b875_0c8177 --label 2441a4 --workdir /github/workspace --rm -e "INPUT_USER" -e "INPUT_PASSWORD" -e "INPUT_REPOSITORY-URL" -e "INPUT_REPOSITORY_URL" -e "INPUT_PACKAGES-DIR" -e "INPUT_PACKAGES_DIR" -e "INPUT_VERIFY-METADATA" -e "INPUT_VERIFY_METADATA" -e "INPUT_SKIP-EXISTING" -e "INPUT_SKIP_EXISTING" -e "INPUT_VERBOSE" -e "INPUT_PRINT-HASH" -e "INPUT_PRINT_HASH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/rebdhuhn/rebdhuhn":"/github/workspace" 2441a4:d52cd77ac7d645c69bfdf09628f5b875  "__token__" "" "" "" "" "" "false" ""
Checking dist/rebdhuhn-0.0.0-py3-none-any.whl: PASSED
Checking dist/rebdhuhn-0.0.0.tar.gz: PASSED
Uploading distributions to https://upload.pypi.org/legacy/
Uploading rebdhuhn-0.0.0-py3-none-any.whl
25l

**Comment by hf-kklein** [comment]
![grafik](https://github.com/Hochfrequenz/rebdhuhn/assets/23094997/ed370111-37ae-4f2e-9af3-36678232ae0c)
https://pypi.org/project/rebdhuhn/

**Comment by hf-krechan** [comment]
yes the whole package setup does not contain tooling to retrieve the version given from a git tag.
I would recommend to switch from the `setup.cfg` and `setup.py` to the `pyproject.toml` approach.

**Comment by hf-kklein** [comment]
fixed with #207 / rebdhuhn 0.2.3  . danke @hf-krechan
